### ISSUE TITLE
Build error gulp browserify 

### ISSUE THREAD

**Issue by rusekr** [versatica/JsSIP#340]
Hello! Trying to build with defaults and 'gulp' command and getting error:

[14:29:07] Starting 'browserify'...
[14:29:07] 'browserify' errored after 806 ms
[14:29:07] TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:167:9)
    at new Buffer (buffer.js:58:10)
    at Concat.add (/home/su/wprojects/jssip-rusekr/node_modules/gulp-header/node_modules/concat-with-sourcemaps/index.js:40:15)
    at DestroyableTransform.TransformStream [as _transform] (/home/su/wprojects/jssip-rusekr/node_modules/gulp-header/index.js:49:12)
    at DestroyableTransform.Transform._read (/home/su/wprojects/jssip-rusekr/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/home/su/wprojects/jssip-rusekr/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/home/su/wprojects/jssip-rusekr/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/home/su/wprojects/jssip-rusekr/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (/home/su/wprojects/jssip-rusekr/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:11)
    at write (/home/su/wprojects/jssip-rusekr/node_modules/vinyl-source-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
[14:29:07] 'dist' errored after 3.85 s

By some debugging helped cutting line 50 from gulpfile.js with contents:

		.pipe(header(BANNER, BANNER_OPTIONS))

Same banner addition after uglify don`t throws this error.

Any suggestion?

**Comment by ibc** [comment]
A fresh `git clone` of JsSIP does perfectly work when running `gulp` on it (after `npm install` of course).

But: you need `gulp-cli` branch 0.4 globally installed as the [BUILDING](https://github.com/versatica/JsSIP/blob/master/BUILDING.md) documentation clearly states.

If you don't want to globally install `gulp-cli` branch 0.4, you can run `node_modules/.bin/gulp` within the JsSIP folder.

**Comment by rusekr** [comment]
Did exactly as you say (removed  npm_modules dir, npm install, gulp-cli 0.4 system-wide, have read BUILDING) and got this error. On fresh clone too. Using nodejs v4.0.0.

**Comment by ibc** [comment]
It seems that it does not work with Node 4.0.0 (I use 0.12.0). I cannot handle this issue for now until `gulp-cli` and `gulp` release a stable version (probably suitable for Node >= 4.0.0).

May you please provide more info on how to avoid the issue? Does it work if `banner()` is called after `uglify()`?  May you extend it?

**Comment by rusekr** [comment]
Tried other banner places in browserify task, works only if I make addition of banner as separate task.

**Comment by rusekr** [comment]
And again - after uglify standart addition of banner works fine.

**Comment by ibc** [comment]
Finally I added `vinly-buffer` which magically fixes the issue:

https://github.com/tracker1/gulp-header/issues/23

**Comment by rusekr** [comment]
Thanks! Commit may be modified by me therefore disappeared but it was dirty hack anyway.
