### ISSUE TITLE
browserify task fails

### ISSUE THREAD

**Issue by ibc** [versatica/JsSIP#382]
By updating node modules (`npm i`) and running `gulp`, browserify fails:

```
[14:03:51] Starting 'browserify'...
[14:03:52] 'browserify' errored after 618 ms
[14:03:52] Error: ENOENT: no such file or directory, lstat '/Users/ibc/src/JsSIP/jssip.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at DestroyableTransform.TransformStream [as _transform] (/Users/ibc/src/JsSIP/node_modules/gulp-header/index.js:38:12)
    at DestroyableTransform.Transform._read (/Users/ibc/src/JsSIP/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/ibc/src/JsSIP/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/ibc/src/JsSIP/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/ibc/src/JsSIP/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Users/ibc/src/JsSIP/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/Users/ibc/src/JsSIP/node_modules/vinyl-buffer/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/ibc/src/JsSIP/node_modules/vinyl-buffer/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
[14:03:52] 'dist' errored after 2.71 s
```

No idea.

**Comment by ibc** [comment]
Ok, it seems that `gulp-header` fails...

**Comment by ibc** [comment]
Found the bug: https://github.com/tracker1/gulp-header/issues/37

So for now let's force `gulp-header` 1.8.2.

**Comment by ibc** [comment]
Fixed.
