### ISSUE TITLE
RTCSecssion terminate does not return

### ISSUE THREAD

**Issue by jim-holmes-vtcsecure** [versatica/JsSIP#452]
If there is a state error 
exception {code: 2, name: "INVALID_STATE_ERROR", status: 8, message: "Invalid status: 8"}code: 2message: "Invalid status: 8"name: "INVALID_STATE_ERROR"status: 8__proto__: Error
    at https://<server>/modules/jssip/dist/jssip.js:682:27
    at Object.5 (https://<server>/modules/jssip/dist/jssip.js:684:4)
    at s (https://<server>/modules/jssip/dist/jssip.js:9:619)
    at https://<server>/modules/jssip/dist/jssip.js:9:670
    at Object.7.../package.json (https://<server>/modules/jssip/dist/jssip.js:12955:18)
    at s (https://<server>/modules/jssip/dist/jssip.js:9:619)
    at e (https://<server>/modules/jssip/dist/jssip.js:9:790)
    at https://<server>/modules/jssip/dist/jssip.js:9:808
    at https://<server>/modules/jssip/dist/jssip.js:9:315
    at https://<server>/modules/jssip/dist/jssip.js:9:321

when calling terminate() the function call will not return.

**Comment by ibc** [comment]
What does "the function call will not return" mean? The [documentation](http://jssip.net/documentation/3.0.x/api/session/#method_terminate) clearly states that, if called in wrong state, the `terminate()` method throws an INVALID_STATE_ERROR.
