### ISSUE TITLE
Import / Require JsSIP Error

### ISSUE THREAD

**Issue by ostrichegret** [versatica/JsSIP#489]
after using 
`npm install --save jssip`

i add this code
`var jssip = require('jssip');`
also try this
`import JsSIP from 'jssip';`

i got this error:
```
error: bundling: Error: Couldn't find preset "env" relative to directory "D:\\RCTWebRTCDemo\\node_modules\\jssip"
    at D:\RCTWebRTCDemo\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (D:\RCTWebRTCDemo\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (D:\RCTWebRTCDemo\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (D:\RCTWebRTCDemo\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (D:\RCTWebRTCDemo\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (D:\RCTWebRTCDemo\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (D:\RCTWebRTCDemo\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (D:\RCTWebRTCDemo\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
TransformError: D:\RCTWebRTCDemo\node_modules\jssip\lib-es5\JsSIP.js: Couldn't find preset "env" relative to directory "D:\\RCTWebRTCDemo\\node_modules\\jssip"
```

i tried to download release file and rename it to jssip.js
`http://jssip.net/download/releases/jssip-3.1.4.js`

add again
`var jssip = require('./jssip.js');`

and i got this:
```
error: bundling: UnableToResolveError: Unable to resolve module `./Utils` from `D:\RCTWebRTCDemo\jssip.js`: Directory D:\RCTWebRTCDemo\Utils doesn't exist
    at ResolutionRequest._loadAsDir (D:/RCTWebRTCDemo/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:485:13)
    at tryResolveSync (D:/RCTWebRTCDemo/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:335:18)
    at tryResolveSync (D:/RCTWebRTCDemo/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:66:12)
    at ResolutionRequest._resolveFileOrDir (D:/RCTWebRTCDemo/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:333:12)
    at ResolutionRequest._resolveNodeDependency (D:/RCTWebRTCDemo/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:341:19)
    at ResolutionRequest.resolveDependency (D:/RCTWebRTCDemo/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:141:29)
    at dependencyNames.map.name (D:/RCTWebRTCDemo/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:59)
    at Array.map (<anonymous>)
    at ResolutionRequest.resolveModuleDependencies (D:/RCTWebRTCDemo/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:42)
    at Promise.resolve.then (D:/RCTWebRTCDemo/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:169:21)
```

How to fix? Thank you

**Comment by ibc** [comment]
Please, use the mailing list for usage questions. The above seems to be a problem within your JS+babel project, rather than being related to JsSIP itself.

**Comment by namnm** [comment]
@ibc Wrong! This is a problem from jssip. We should add the .babelrc file into npmignore

**Comment by ibc** [comment]
Sorry, what?

**Comment by namnm** [comment]
I think we should not publish the .babelrc file together in the npm package. We can have it in git repo and our local development env to transpile the code to es5 but we should not publish it to npm.

The code to be published to npm should have been transpiled already (lib-es5 dir) or untranspiled (lib dir). If user choose to use the tranpiled, they dont need to do anything. If they choose to use the untranpiled, they want to use there own config instead, so if we put .babelrc in the package, it will mess up with user's config.

Hope you understand

**Comment by ibc** [comment]
I've been reading about this and indeed it seems that including `.babelrc` in NPM modules overrides the user provided Babel settings within his app root folder. Is this, right?

**Comment by namnm** [comment]
Yes..

**Comment by ibc** [comment]
ok, jssip NPM 3.3.5 is out without `.babelrc`.
